{
    "name": "Majal Dashboards",
    "summary": "Board dashboards for construction, facilities and the estate, "
               "over SQL analysis views",
    "version": "18.0.1.0.0",
    "category": "Construction",
    "license": "LGPL-3",
    "author": "Mohamed Amer",
    "website": "https://github.com/Mohamed95Amer/Mohamed95Amer",
    "depends": [
        "board",
        "spreadsheet_dashboard",
        "construction_report",
        "construction_progress_billing",
        "construction_subcontractor",
        "construction_change_order",
        "construction_rfi",
        "construction_defect",
        "construction_hse",
        "facility_asset",
        "facility_workorder",
        "facility_sla",
        "facility_contract",
        "purchase",
        "majal_workforce",
        "construction_material",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/construction_report_views.xml",
        "views/facility_report_views.xml",
        "views/estate_report_views.xml",
        "views/procurement_report_views.xml",
        "views/operational_views.xml",
        "views/dashboards.xml",
        "views/menus.xml",
    ],
    "installable": True,
}
