import base64

from odoo import models
from odoo.tools import file_open


class ConstructionBimDemo(models.AbstractModel):
    """Load the sample model from disk rather than inlining it as base64.

    A demo IFC pasted into an XML record would be unreadable and unreviewable.
    The file next to this module can be opened in any IFC viewer to see exactly
    what the demo contains — three walls and a slab on one storey, generated by
    static/demo/generate_sample.py.
    """

    _name = "construction.bim.demo"
    _description = "BIM Demo Loader"

    def _load_demo_model(self):
        model = self.env.ref(
            "construction_bim.bim_model_al_noor_l03", raise_if_not_found=False)
        if not model:
            return False
        with file_open("construction_bim/static/demo/al-noor-l03.ifc", "rb") as handle:
            model.write({
                "ifc_file": base64.b64encode(handle.read()),
                "ifc_filename": "al-noor-l03.ifc",
            })
        model.action_index()
        model.action_make_current()
        return True

    def _link_demo_records(self):
        """Attach a live RFI and a defect to two of the walls.

        This is the whole argument for the module in one screen: the wall with
        the unanswered question is red in the model, and clicking it opens the
        question.
        """
        model = self.env.ref(
            "construction_bim.bim_model_al_noor_l03", raise_if_not_found=False)
        if not model:
            return False
        element_model = self.env["construction.bim.element"]
        rfi = self.env["construction.rfi"].search(
            [("project_id", "=", model.project_id.id),
             ("state", "not in", ("closed", "cancelled"))], limit=1)
        defect = self.env["construction.defect"].search(
            [("project_id", "=", model.project_id.id)], limit=1)

        if rfi:
            element_model.link_element(
                model.id, "2O2Fr$t4X7Zf8NOew3FLIE", {"rfi_id": rfi.id})
        if defect:
            element_model.link_element(
                model.id, "3Xs9pQ1nD2yQ8mWJk4LzAB", {"defect_id": defect.id})
        element_model.link_element(
            model.id, "5SlAbGuId0000000000000",
            {"note": "Slab level to be confirmed against the survey."})
        return True
