import base64

from dateutil.relativedelta import relativedelta

from odoo import fields, models
from odoo.tools import file_open


class ConstructionBimDemo(models.AbstractModel):
    """Load the sample model from disk rather than inlining it as base64.

    A demo IFC pasted into an XML record would be unreadable and unreviewable.
    The file next to this module can be opened in any IFC viewer to see exactly
    what the demo contains — three walls and a slab on one storey, generated by
    static/demo/generate_sample.py.
    """

    _name = "construction.bim.demo"
    _description = "BIM Demo Loader"

    def _load_demo_model(self):
        model = self.env.ref(
            "construction_bim.bim_model_al_noor_l03", raise_if_not_found=False)
        if not model:
            return False
        with file_open("construction_bim/static/demo/al-noor-l03.ifc", "rb") as handle:
            model.write({
                "ifc_file": base64.b64encode(handle.read()),
                "ifc_filename": "al-noor-l03.ifc",
            })
        model.action_index()
        model.action_make_current()
        return True

    def _link_demo_records(self):
        """Attach a live RFI and a defect to two of the walls.

        This is the whole argument for the module in one screen: the wall with
        the unanswered question is red in the model, and clicking it opens the
        question.
        """
        model = self.env.ref(
            "construction_bim.bim_model_al_noor_l03", raise_if_not_found=False)
        if not model:
            return False
        element_model = self.env["construction.bim.element"]
        rfi = self.env["construction.rfi"].search(
            [("project_id", "=", model.project_id.id),
             ("state", "not in", ("closed", "cancelled"))], limit=1)
        defect = self.env["construction.defect"].search(
            [("project_id", "=", model.project_id.id)], limit=1)

        if rfi:
            element_model.link_element(
                model.id, "2O2Fr$t4X7Zf8NOew3FLIE", {"rfi_id": rfi.id})
        if defect:
            element_model.link_element(
                model.id, "3Xs9pQ1nD2yQ8mWJk4LzAB", {"defect_id": defect.id})
        element_model.link_element(
            model.id, "5SlAbGuId0000000000000",
            {"note": "Slab level to be confirmed against the survey."})
        self._link_demo_programme(model, element_model)
        return True

    def _link_demo_programme(self, model, element_model):
        """Put the elements on a programme so 4D has something to play.

        The dates are the tasks' own. That is the argument for driving 4D from
        the programme rather than from a separate schedule kept inside the
        model: there is only one set of dates, and it is the one the site is
        working to.
        """
        task_model = self.env["project.task"]
        today = fields.Date.context_today(self)
        sequence = [
            ("5SlAbGuId0000000000000", "Slab pour — Level 03", 0, 6),
            ("2O2Fr$t4X7Zf8NOew3FLIE", "Blockwork — grid A", 7, 20),
            ("4Kl0mNoPq1RsT2uVwXyZaB", "Core wall — Level 03", 10, 24),
            ("3Xs9pQ1nD2yQ8mWJk4LzAB", "Curtain wall — grid F", 25, 45),
        ]
        for global_id, name, starts_in, ends_in in sequence:
            task = task_model.search([
                ("project_id", "=", model.project_id.id), ("name", "=", name),
            ], limit=1)
            if not task:
                task = task_model.create({
                    "name": name, "project_id": model.project_id.id})
            task.write({
                "date_assign": today + relativedelta(days=starts_in),
                "date_deadline": today + relativedelta(days=ends_in),
            })
            element_model.link_element(model.id, global_id, {"task_id": task.id})
        return True
