{
    "name": "Majal Field Offline",
    "summary": "Bounded offline field workspace with conflict-safe sync",
    "version": "18.0.1.1.0",
    "category": "Majal/Field Operations",
    "license": "LGPL-3",
    "depends": [
        "web",
        "construction_defect",
        "construction_form",
        "construction_daily_log",
        "construction_drawing",
        "facility_asset",
        "facility_workorder",
        "majal_administration",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/offline_security.xml",
        "views/field_app_templates.xml",
        "views/menus.xml",
    ],
    "application": True,
    "installable": True,
}
