"use client";

import { useState, type FormEvent } from "react";

interface Preferences { language: "en" | "ar"; in_app_notifications: boolean; email_notifications: boolean; sms_notifications: boolean; whatsapp_notifications: boolean; marketing_notifications: boolean; }

export function NotificationPreferencesForm({ initial, arabic = false }: { initial: Preferences; arabic?: boolean }) {
  const t = (en: string, ar: string) => arabic ? ar : en;
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(null); const form = new FormData(event.currentTarget); const response = await fetch("/api/account/preferences", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ language: form.get("language"), inAppNotifications: form.get("in_app") === "on", emailNotifications: form.get("email") === "on", smsNotifications: form.get("sms") === "on", whatsappNotifications: form.get("whatsapp") === "on", marketingNotifications: form.get("marketing") === "on" }) }); setBusy(false); setMessage(response.ok ? t("Preferences saved.", "تم حفظ التفضيلات.") : t("Could not save preferences.", "تعذر حفظ التفضيلات.")); if (response.ok && form.get("language") !== initial.language) window.location.reload(); }
  return <form onSubmit={submit} className="card mt-6 space-y-5 p-6"><div><label className="label" htmlFor="preference-language">{t("Language", "اللغة")}</label><select id="preference-language" name="language" className="input mt-1" defaultValue={initial.language}><option value="en">English</option><option value="ar">العربية</option></select><p className="mt-1 text-xs text-ink-muted">{t("Arabic navigation and right-to-left layout are available now; full catalogue translation depends on vendor content.", "التنقل بالعربية والتخطيط من اليمين إلى اليسار متاحان الآن؛ وتعتمد ترجمة بيانات المنتجات على المحتوى الذي يقدمه المتجر.")}</p></div><fieldset><legend className="label">{t("Operational updates", "تحديثات الطلبات")}</legend><input type="hidden" name="in_app" value="on" /><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-3 rounded-xl border border-jade-900/10 bg-jade-50 p-3 text-sm"><input type="checkbox" checked disabled /><span>{t("In-app order & security records", "سجلات الطلب والأمان داخل التطبيق")}</span></label>{[["email", t("Email", "البريد الإلكتروني"), initial.email_notifications], ["sms", t("SMS", "الرسائل النصية"), initial.sms_notifications], ["whatsapp", "WhatsApp", initial.whatsapp_notifications]].map(([name, label, checked]) => <label key={String(name)} className="flex items-center gap-3 rounded-xl border border-jade-900/10 p-3 text-sm"><input name={String(name)} type="checkbox" defaultChecked={Boolean(checked)} /><span>{String(label)}</span></label>)}</div><p className="mt-2 text-xs text-ink-muted">{t("In-app order and security records remain active. Email, SMS and WhatsApp choices are stored but require verified provider connections before messages are sent.", "تبقى سجلات الطلب والأمان داخل التطبيق نشطة. تُحفظ تفضيلات البريد والرسائل النصية وواتساب، لكنها تحتاج ربط مزودي خدمات معتمدين قبل إرسال الرسائل.")}</p></fieldset><label className="flex items-start gap-3 rounded-xl bg-jade-50 p-4 text-sm"><input name="marketing" type="checkbox" defaultChecked={initial.marketing_notifications} className="mt-0.5" /><span><strong>{t("Offers and editorial updates", "العروض والمحتوى الجديد")}</strong><span className="mt-1 block text-xs text-ink-muted">{t("Optional marketing only. Order, security and delivery messages are treated separately.", "تسويق اختياري فقط. تُعامل رسائل الطلب والأمان والتوصيل بشكل منفصل.")}</span></span></label>{message && <p role="status" className="text-sm text-jade-700">{message}</p>}<button className="btn-primary" disabled={busy}>{busy ? t("Saving…", "جارٍ الحفظ…") : t("Save preferences", "حفظ التفضيلات")}</button></form>;
}
