{
    "name": "Majal Experience",
    "summary": "Majal construction and facilities workspaces",
    "version": "18.0.1.1.0",
    "category": "Construction",
    "license": "LGPL-3",
    "author": "Majal",
    "depends": [
        "web",
        "website",
        "mail",
        "board",
        "project_todo",
        "spreadsheet_dashboard",
        "account",
        "purchase",
        "stock",
        "project",
        "maintenance",
        "hr",
        "construction_base",
        "construction_boq",
        "construction_drawing",
        "construction_rfi",
        "construction_submittal",
        "construction_pin",
        "construction_planning",
        "construction_defect",
        "construction_daily_log",
        "construction_form",
        "construction_progress_billing",
        "construction_change_order",
        "construction_subcontractor",
        "construction_report",
        "construction_hse",
        "construction_tender",
        "construction_material",
        "construction_meeting",
        "construction_bim",
        "construction_whatsapp",
        "construction_portal",
        "construction_dashboard",
        "facility_asset",
        "facility_workorder",
        "facility_sla",
        "facility_contract",
        "facility_inventory",
        "facility_portal",
        "facility_floorplan",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/construction_home_views.xml",
        "views/my_day_views.xml",
        "views/facility_home_views.xml",
        "views/project_workspace_views.xml",
        "views/workspace_hub_views.xml",
        "views/dashboard_hub_views.xml",
        "views/login_branding.xml",
        "views/majal_branding.xml",
        "views/app_icon_branding.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "construction_ui/static/src/app_launcher/app_launcher.xml",
            "construction_ui/static/src/app_launcher/app_launcher.scss",
            "construction_ui/static/src/home/construction_home.js",
            "construction_ui/static/src/home/construction_home.xml",
            "construction_ui/static/src/home/construction_home.scss",
            "construction_ui/static/src/facility_home/facility_home.js",
            "construction_ui/static/src/facility_home/facility_home.xml",
            "construction_ui/static/src/facility_home/facility_home.scss",
            "construction_ui/static/src/my_day/my_day.js",
            "construction_ui/static/src/my_day/my_day.xml",
            "construction_ui/static/src/my_day/my_day.scss",
            "construction_ui/static/src/workspace_hub/workspace_hub.js",
            "construction_ui/static/src/workspace_hub/workspace_hub.xml",
            "construction_ui/static/src/workspace_hub/workspace_hub.scss",
            "construction_ui/static/src/dashboard_hub/dashboard_hub.js",
            "construction_ui/static/src/dashboard_hub/dashboard_hub.xml",
            "construction_ui/static/src/dashboard_hub/dashboard_hub.scss",
            "construction_ui/static/src/sidebar/majal_sidebar.js",
            "construction_ui/static/src/sidebar/majal_sidebar.xml",
            "construction_ui/static/src/sidebar/majal_sidebar.scss",
            "construction_ui/static/src/scss/backend.scss",
            "construction_ui/static/src/scss/rtl.scss",
        ],
        "web.assets_frontend": [
            "construction_ui/static/src/scss/login.scss",
            "construction_ui/static/src/scss/portal.scss",
        ],
    },
    "application": False,
    "installable": True,
}
