{
    "name": "Construction Suite UI",
    "summary": "Modern Odoo 19-inspired home, navigation and visual polish",
    "version": "18.0.1.0.0",
    "category": "Construction",
    "license": "LGPL-3",
    "author": "Mohamed Amer",
    "website": "https://github.com/Mohamed95Amer/Mohamed95Amer",
    "depends": [
        "web",
        "board",
        "construction_base",
        "construction_boq",
        "construction_drawing",
        "construction_rfi",
        "construction_submittal",
        "construction_pin",
        "construction_planning",
        "construction_defect",
        "construction_daily_log",
        "construction_form",
        "construction_progress_billing",
        "construction_change_order",
        "construction_subcontractor",
        "facility_asset",
        "facility_workorder",
        "facility_floorplan",
    ],
    "data": [
        "views/construction_home_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "construction_ui/static/src/home/construction_home.js",
            "construction_ui/static/src/home/construction_home.xml",
            "construction_ui/static/src/home/construction_home.scss",
            "construction_ui/static/src/scss/backend.scss",
        ],
    },
    "application": False,
    "installable": True,
}
