{
    "name": "Majal Experience",
    "summary": "Majal construction and facilities workspaces",
    "version": "18.0.1.0.0",
    "category": "Construction",
    "license": "LGPL-3",
    "author": "Majal",
    "depends": [
        "web",
        "board",
        "construction_base",
        "construction_boq",
        "construction_drawing",
        "construction_rfi",
        "construction_submittal",
        "construction_pin",
        "construction_planning",
        "construction_defect",
        "construction_daily_log",
        "construction_form",
        "construction_progress_billing",
        "construction_change_order",
        "construction_subcontractor",
        "facility_asset",
        "facility_workorder",
        "facility_floorplan",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/construction_home_views.xml",
        "views/facility_home_views.xml",
        "views/project_workspace_views.xml",
        "views/workspace_hub_views.xml",
        "views/majal_branding.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "construction_ui/static/src/home/construction_home.js",
            "construction_ui/static/src/home/construction_home.xml",
            "construction_ui/static/src/home/construction_home.scss",
            "construction_ui/static/src/facility_home/facility_home.js",
            "construction_ui/static/src/facility_home/facility_home.xml",
            "construction_ui/static/src/facility_home/facility_home.scss",
            "construction_ui/static/src/workspace_hub/workspace_hub.js",
            "construction_ui/static/src/workspace_hub/workspace_hub.xml",
            "construction_ui/static/src/workspace_hub/workspace_hub.scss",
            "construction_ui/static/src/scss/backend.scss",
        ],
    },
    "application": False,
    "installable": True,
}
