import type { Metadata } from "next";
import { PolicyPage } from "@/components/PolicyPage";

export const metadata: Metadata = { title: "Privacy policy", description: "How Get Gold handles customer, vendor, delivery partner and marketplace data.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <PolicyPage eyebrow="Your information" title="Privacy policy" intro="Get Gold collects only the information needed to operate accounts, reservations, partner verification and marketplace safety." sections={[
    { title: "Information we collect", bullets: ["Account details such as name, email and phone number.", "Reservation, delivery address and location pin, purchase, review and support history.", "Saved listings, price-alert targets, notification choices and referral attribution.", "Gold-request preferences and any optional reference image; store-visit time, phone and note.", "A minimal identity-check record for each order: provider reference, resident or visitor route, pass/fail status and timestamps.", "Vendor identity, licence, address and verification documents.", "Privacy-minimal funnel events such as marketplace, product, comparison and checkout steps; search text itself is not stored in analytics.", "Technical and security information such as timestamps, IP address and audit events."] },
    { title: "Mandatory order identity check", paragraphs: ["Before every new order, UAE residents use Didit’s hosted service to capture the front and back of an Emirates ID and complete a liveness and face-match check. Visitors use a passport and boarding pass and complete the same face check.", "Document images, boarding-pass images, selfies and biometric templates are collected and processed by Didit. Get Gold does not receive or store those files. It receives the provider’s outcome needed to authorize one order. Biometric processing requires explicit notice and consent in the hosted flow."] },
    { title: "How we use information", paragraphs: ["We use information to authenticate users, identify the person placing each order, display account history, create price-locked reservations, notify users about orders and watched listings, attribute referrals, measure the marketplace funnel, verify vendors, prevent overselling and fraud, moderate reviews, provide support and maintain legally relevant records."] },
    { title: "Who receives information", paragraphs: ["Didit processes the identity documents and live face scan required for the selected verification route. A vendor receives the customer and reservation information needed to confirm and fulfil that vendor’s order, plus confirmation that the check passed—not the identity images.", "Approved vendors can review open gold requests. An optional reference image stays in private storage and is shared through a short-lived link; competing offer prices are not shown to other vendors. An approved delivery company receives only the fulfilment information needed after it is assigned. Infrastructure, authentication, hosting and storage providers process information on Get Gold’s behalf. We do not publish private documents."] },
    { title: "Retention and security", paragraphs: ["Reservation price snapshots, the minimal identity-check outcome and audit records are retained to preserve transaction integrity. Identity document and biometric retention is controlled in Didit and must be configured to the shortest period allowed by the applicable contract and legal obligations.", "Privacy-minimal funnel events are automatically removed after about 13 months. Reference images and visit/request details should be deleted or anonymized when they are no longer reasonably needed for matching, support or a legal obligation. Access controls, private storage, expiring links and server-side authorization are used to restrict sensitive data."] },
    { title: "Your choices", paragraphs: ["You may turn off optional marketing and external notification channels, remove saved listings, deactivate price alerts, ask to access or correct account information, or raise a deletion request. In-account order and security records remain available. Some transaction, fraud-prevention or legal records may need to be retained."] },
  ]} />;
}
