#!/usr/bin/env bash
# Vendor the OCA modules pinned in oca-repos.yml into oca-addons/.
#
# For each repo: shallow-clone at the pinned commit into a temp dir, copy only
# the whitelisted module directories into oca-addons/, and record provenance
# in oca-addons/OCA_SOURCES.md. The result IS committed to this repository.
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
YML="$HERE/oca-repos.yml"
DEST="$HERE/oca-addons"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

python3 - "$YML" <<'EOF' > "$TMP/repos.tsv"
import sys, re
repo = url = commit = None
rows = []
for line in open(sys.argv[1]):
    if re.match(r'^  [a-z0-9-]+:\s*$', line):
        repo = line.strip().rstrip(':'); url = commit = None; mods = []
        rows.append([repo, mods, None, None])
    elif m := re.match(r'^    url:\s*(\S+)', line):
        rows[-1][2] = m.group(1)
    elif m := re.match(r'^    commit:\s*(\S+)', line):
        rows[-1][3] = m.group(1)
    elif m := re.match(r'^      - (\S+)', line):
        rows[-1][1].append(m.group(1))
for repo, mods, url, commit in rows:
    print(f"{repo}\t{url}\t{commit}\t{','.join(mods)}")
EOF

mkdir -p "$DEST"
MANIFEST="$DEST/OCA_SOURCES.md"
{
    echo "# Vendored OCA module provenance"
    echo
    echo "Generated by scripts/fetch-oca.sh from oca-repos.yml. Do not edit modules in place —"
    echo "update the pin in oca-repos.yml and re-run the script."
    echo
    echo "| Repo | Commit | Modules |"
    echo "|---|---|---|"
} > "$MANIFEST"

while IFS=$'\t' read -r repo url commit modules; do
    echo ">> $repo @ $commit"
    dir="$TMP/$repo"
    git init -q "$dir"
    git -C "$dir" remote add origin "$url"
    git -C "$dir" fetch -q --depth 1 origin "$commit"
    git -C "$dir" checkout -q FETCH_HEAD
    IFS=',' read -ra mods <<< "$modules"
    for mod in "${mods[@]}"; do
        if [ ! -f "$dir/$mod/__manifest__.py" ]; then
            echo "!! MISSING: $repo/$mod has no __manifest__.py at pinned commit" >&2
            exit 1
        fi
        if ! grep -Eq '"installable":\s*True|'"'"'installable'"'"':\s*True' "$dir/$mod/__manifest__.py" \
           && grep -Eq 'installable' "$dir/$mod/__manifest__.py"; then
            echo "!! NOT INSTALLABLE: $repo/$mod is marked installable: False" >&2
            exit 1
        fi
        rm -rf "$DEST/$mod"
        cp -r "$dir/$mod" "$DEST/$mod"
        echo "   + $mod"
    done
    echo "| OCA/$repo | \`$commit\` | ${modules//,/, } |" >> "$MANIFEST"
done < "$TMP/repos.tsv"

echo ">> Done. Vendored modules in $DEST"
