#!/usr/bin/env bash
# Vendor third-party Odoo modules pinned in a repos manifest into a dest dir.
#
#   scripts/fetch-vendor.sh [manifest.yml] [dest-dir]
#
# Defaults to oca-repos.yml -> oca-addons/. Also used for third-party
# (non-OCA) community modules via:
#   scripts/fetch-vendor.sh third-party-repos.yml third-party-addons
#
# For each repo: shallow-clone at the pinned commit into a temp dir, copy only
# the whitelisted module directories into the dest, and record provenance in
# <dest>/SOURCES.md. The vendored result IS committed to this repository.
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
YML="${1:-$HERE/oca-repos.yml}"
DEST="${2:-$HERE/oca-addons}"
[ -f "$YML" ] || { echo "manifest not found: $YML" >&2; exit 1; }
case "$DEST" in /*) : ;; *) DEST="$HERE/$DEST" ;; esac
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

python3 - "$YML" <<'EOF' > "$TMP/repos.tsv"
import sys, re
rows = []
for line in open(sys.argv[1]):
    if re.match(r'^  [a-z0-9-]+:\s*$', line):
        rows.append([line.strip().rstrip(':'), [], None, None])
    elif m := re.match(r'^    url:\s*(\S+)', line):
        rows[-1][2] = m.group(1)
    elif m := re.match(r'^    commit:\s*(\S+)', line):
        rows[-1][3] = m.group(1)
    elif m := re.match(r'^      - (\S+)', line):
        rows[-1][1].append(m.group(1))
for repo, mods, url, commit in rows:
    print(f"{repo}\t{url}\t{commit}\t{','.join(mods)}")
EOF

mkdir -p "$DEST"
MANIFEST="$DEST/SOURCES.md"
{
    echo "# Vendored module provenance"
    echo
    echo "Generated by scripts/fetch-vendor.sh. Do not edit modules in place —"
    echo "update the pin in the repos manifest and re-run the script."
    echo
    echo "| Source | Commit | Modules |"
    echo "|---|---|---|"
} > "$MANIFEST"

while IFS=$'\t' read -r repo url commit modules; do
    echo ">> $repo @ $commit"
    dir="$TMP/$repo"
    git init -q "$dir"
    git -C "$dir" remote add origin "$url"
    git -C "$dir" fetch -q --depth 1 origin "$commit"
    git -C "$dir" checkout -q FETCH_HEAD
    IFS=',' read -ra mods <<< "$modules"
    for mod in "${mods[@]}"; do
        if [ ! -f "$dir/$mod/__manifest__.py" ]; then
            echo "!! MISSING: $repo/$mod has no __manifest__.py at pinned commit" >&2
            exit 1
        fi
        if grep -Eq "installable" "$dir/$mod/__manifest__.py" \
           && ! grep -Eq "installable[\"']?\s*:\s*True" "$dir/$mod/__manifest__.py"; then
            echo "!! NOT INSTALLABLE: $repo/$mod is marked installable: False" >&2
            exit 1
        fi
        rm -rf "$DEST/$mod"
        cp -r "$dir/$mod" "$DEST/$mod"
        echo "   + $mod"
    done
    echo "| $url | \`$commit\` | ${modules//,/, } |" >> "$MANIFEST"
done < "$TMP/repos.tsv"

echo ">> Done. Vendored modules in $DEST"
